services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_LICENSE_ACTIVATION_KEY=enterprise-poc-key
      - N8N_LICENSE_TENANT_ID=enterprise-poc
      - N8N_LICENSE_SERVER_URL=http://localhost
      - N8N_LICENSE_OFFLINE_MODE=true
	- N8N_HOST: n8n-production-8fb1.up.railway.app
     - N8N_PROTOCOL: https
     - N8N_PORT: 443
     - WEBHOOK_URL: https://n8n-production-8fb1.up.railway.app/
     - N8N_EDITOR_BASE_URL: https://n8n-production-8fb1.up.railway.app/
    volumes:
      - ~/.n8n:/home/node/.n8n

