services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8nio/n8n:latest           # official image
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      # --- Licensing (Enterprise only) ---
      - N8N_LICENSE_ACTIVATION_KEY=enterprise-poc-key
      - N8N_LICENSE_TENANT_ID=enterprise-poc
      - N8N_LICENSE_SERVER_URL=https://n8n-production-8fb1.up.railway.app
      - N8N_LICENSE_OFFLINE_MODE=true

      # --- Core URL/host settings ---
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n-production-8fb1.up.railway.app
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=https://n8n-production-8fb1.up.railway.app

      # --- Webhooks (external URL seen by WhatsApp or any caller) ---
      - WEBHOOK_URL=https://n8n-production-8fb1.up.railway.app
      # Omit the tunnel when you already have a public URL.
      # - WEBHOOK_TUNNEL_URL=https://n8n-production-8fb1.up.railway.app

      # --- Recommended hardening + ops ---
      - N8N_SECURE_COOKIE=true
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_ENCRYPTION_KEY=replace-with-strong-random-string
      # - N8N_DIAGNOSTICS_ENABLED=false
      # - N8N_PERSONALIZATION_ENABLED=false

    volumes:
      - ./n8n_data:/home/node/.n8n
