services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-n8n-osint:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_LICENSE_ACTIVATION_KEY=enterprise-poc-key
      - N8N_LICENSE_TENANT_ID=enterprise-poc
      - N8N_LICENSE_SERVER_URL=http://localhost
      - N8N_LICENSE_OFFLINE_MODE=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
	- N8N_EXTERNAL_URL=https://n8n-production-8fb1.up.railway.app/
	- WEBHOOK_URL=https://n8n-production-8fb1.up.railway.app/
	- N8N_PROTOCOL=https"